### PR TITLE
Create composer.json, closes #6

### LINKED ISSUE #6: Please add composer.json
Like:

```
{
  "name": "justintadlock/butterbean",
  "description": "A neat little post meta framework.",
  "license": "GPL-2.0",
  "require": {}
}
```

or similar.

### PR DESCRIPTION
**Pull request by QWp6t**
Guess what. You'll never believe this. I actually read the contributing guidelines! :scream: 

> Please don't make pull requests against the `master` branch. This is the latest, stable code. You can make a pull request against one of the point branches or the `dev` (future release) branch.

Unfortunately, you only have a `master` branch, so I'm targeting it.

### CODE REVIEW

**Comment by tomjn** [comment]
A require for composer installers is missing, which is needed if you're going to use `wordpress-plugin` as the package type

**Comment by justintadlock** [comment]
I'm cool with adding Composer support.  It's not something I use, so I just need the go-ahead from a couple of folks who use it on when a pull request is definitely ready.

**Comment by tomjn** [comment]
The require statement is all that's needed, Im on a mobile connection at
the moment else Id add it myself ( can you add directly to other peoples
pull requests? )

**Comment by justintadlock** [comment]
No idea about that.  Sometimes, I don't use PRs though.  I just grab the patch and apply it locally first anyway.

**Comment by m-e-h** [comment]
If this PR is gonna get updated, maybe also do away with the 'acf' keyword?

**Comment by slaFFik** [comment]
And add `custom post type` & `cpt` keywords :)

**Pull request closed without merging**
